-- V7: Replace all Cloudinary image URLs with local paths.
-- The Cloudinary free tier is exhausted and images carry Gemini watermarks.
-- Local product images are served from vpnexues-ui/public/images/products/.

UPDATE products SET image_url = '/images/products/Almonds.jpg' WHERE slug = 'almonds';
UPDATE products SET image_url = '/images/products/Aloe Vera Juice.jpg' WHERE slug = 'aloe-vera-juice';
UPDATE products SET image_url = '/images/products/Alphonso Mango.jpg' WHERE slug = 'alphonso-mango';
UPDATE products SET image_url = '/images/products/Amla Juice.jpg' WHERE slug = 'amla-juice';
UPDATE products SET image_url = '/images/products/Fresh Apricots.jpg' WHERE slug = 'apricots';
UPDATE products SET image_url = '/images/products/Asafoetida.jpg' WHERE slug = 'asafoetida-hing';
UPDATE products SET image_url = '/images/products/Asparagus.jpg' WHERE slug = 'asparagus';
UPDATE products SET image_url = '/images/products/Baby Spinach.jpg' WHERE slug = 'baby-spinach';
UPDATE products SET image_url = '/images/products/Banana Blossom.jpg' WHERE slug = 'banana-blossom';
UPDATE products SET image_url = '/images/products/Banana Flower.jpg' WHERE slug = 'banana-flower';
UPDATE products SET image_url = '/images/products/Barley Water.jpg' WHERE slug = 'barley-water';
UPDATE products SET image_url = '/images/products/Basmati Rice.jpg' WHERE slug = 'basmati-rice';
UPDATE products SET image_url = '/images/products/Beetroot.jpg' WHERE slug = 'beetroot';
UPDATE products SET image_url = '/images/products/Bell Peppers Mix.jpg' WHERE slug = 'bell-peppers-mix';
UPDATE products SET image_url = '/images/products/Bitter Gourd.jpg' WHERE slug = 'bitter-gourd';
UPDATE products SET image_url = '/images/products/Bitter Melon.jpg' WHERE slug = 'bitter-melon';
UPDATE products SET image_url = '/images/products/Fresh Blueberries.jpg' WHERE slug = 'blueberries';
UPDATE products SET image_url = '/images/products/Bottle Gourd.jpg' WHERE slug = 'bottle-gourd';
UPDATE products SET image_url = '/images/products/Broccoli Head.jpg' WHERE slug = 'broccoli-head';
UPDATE products SET image_url = '/images/products/Brown Rice.jpg' WHERE slug = 'brown-rice';
UPDATE products SET image_url = '/images/products/Premium Dairy Butter.jpg' WHERE slug = 'butter';
UPDATE products SET image_url = '/images/products/Butterhead Lettuce.jpg' WHERE slug = 'butterhead-lettuce';
UPDATE products SET image_url = '/images/products/Cantaloupe Melon.jpg' WHERE slug = 'cantaloupe-melon';
UPDATE products SET image_url = '/images/products/Green Cardamom.jpg' WHERE slug = 'cardamom-green';
UPDATE products SET image_url = '/images/products/Carrot-Ginger Juice.jpg' WHERE slug = 'carrot-ginger-juice';
UPDATE products SET image_url = '/images/products/Cashew Nuts.jpg' WHERE slug = 'cashew-nuts';
UPDATE products SET image_url = '/images/products/Cauliflower.jpg' WHERE slug = 'cauliflower';
UPDATE products SET image_url = '/images/products/Celery.jpg' WHERE slug = 'celery';
UPDATE products SET image_url = '/images/products/Cheese.jpg' WHERE slug = 'cheese';
UPDATE products SET image_url = '/images/products/Fresh Cherries.jpg' WHERE slug = 'cherries';
UPDATE products SET image_url = '/images/products/Cherry Tomatoes.jpg' WHERE slug = 'cherry-tomatoes';
UPDATE products SET image_url = '/images/products/Chia Seeds.jpg' WHERE slug = 'chia-seeds';
UPDATE products SET image_url = '/images/products/Chickpeas.jpg' WHERE slug = 'chickpeas';
UPDATE products SET image_url = '/images/products/Chilli Peppers.jpg' WHERE slug = 'chilli-peppers';
UPDATE products SET image_url = '/images/products/Cinnamon Sticks.jpg' WHERE slug = 'cinnamon-sticks';
UPDATE products SET image_url = '/images/products/Cloves.jpg' WHERE slug = 'cloves';
UPDATE products SET image_url = '/images/products/Cluster Beans.jpg' WHERE slug = 'cluster-beans';
UPDATE products SET image_url = '/images/products/Coconut Fresh.jpg' WHERE slug = 'coconut-fresh';
UPDATE products SET image_url = '/images/products/Coconut Milk.jpg' WHERE slug = 'coconut-milk';
UPDATE products SET image_url = '/images/products/Tender Coconut Water.jpg' WHERE slug = 'coconut-water';
UPDATE products SET image_url = '/images/products/Cold Pressed Coconut Oil.jpg' WHERE slug = 'cold-pressed-coconut-oil';
UPDATE products SET image_url = '/images/products/Cold-Pressed Juice Mix.jpg' WHERE slug = 'cold-pressed-juice-mix';
UPDATE products SET image_url = '/images/products/Colocasia Leaves.jpg' WHERE slug = 'colocasia-leaves';
UPDATE products SET image_url = '/images/products/Coriander Seeds.jpg' WHERE slug = 'coriander';
UPDATE products SET image_url = '/images/products/Coriander Seeds.jpg' WHERE slug = 'coriander-seeds';
UPDATE products SET image_url = '/images/products/Crunchy Coated Peanuts.jpg' WHERE slug = 'crunchy-coated-peanuts';
UPDATE products SET image_url = '/images/products/Cucumber.jpg' WHERE slug = 'cucumber';
UPDATE products SET image_url = '/images/products/Cumin Seeds.jpg' WHERE slug = 'cumin-seeds';
UPDATE products SET image_url = '/images/products/Premium Fresh Curd.jpg' WHERE slug = 'curd';
UPDATE products SET image_url = '/images/products/Curry Leaves.jpg' WHERE slug = 'curry-leaves';
UPDATE products SET image_url = '/images/products/Custard Apple.jpg' WHERE slug = 'custard-apple';
UPDATE products SET image_url = '/images/products/Dates Medjool.jpg' WHERE slug = 'dates-medjool';
UPDATE products SET image_url = '/images/products/Dragon Fruit.jpg' WHERE slug = 'dragon-fruit-white';
UPDATE products SET image_url = '/images/products/Dried Chilli Flakes.jpg' WHERE slug = 'dried-chilli-flakes';
UPDATE products SET image_url = '/images/products/Dried Coconut (Kopra).jpg' WHERE slug = 'dried-coconut-kopra';
UPDATE products SET image_url = '/images/products/Dried Fenugreek Leaves (Kasuri Methi).jpg' WHERE slug = 'dried-fenugreek-leaves';
UPDATE products SET image_url = '/images/products/Dried Mango Powder (Amchur).jpg' WHERE slug = 'dried-mango-powder';
UPDATE products SET image_url = '/images/products/Drumstick Moringa.jpg' WHERE slug = 'drumstick-moringa';
UPDATE products SET image_url = '/images/products/Dry Red Chilli.jpg' WHERE slug = 'dry-red-chilli';
UPDATE products SET image_url = '/images/products/Durian.jpg' WHERE slug = 'durian';
UPDATE products SET image_url = '/images/products/Eggplant.jpg' WHERE slug = 'eggplant';
UPDATE products SET image_url = '/images/products/Farm Fresh Cow Ghee.jpg' WHERE slug = 'farm-fresh-cow-ghee';
UPDATE products SET image_url = '/images/products/Fennel Bulb.jpg' WHERE slug = 'fennel-bulb';
UPDATE products SET image_url = '/images/products/Fenugreek Seeds.jpg' WHERE slug = 'fenugreek-seeds';
UPDATE products SET image_url = '/images/products/Fresh Figs.jpg' WHERE slug = 'fig';
UPDATE products SET image_url = '/images/products/Flaxseeds.jpg' WHERE slug = 'flaxseeds';
UPDATE products SET image_url = '/images/products/Free Range Eggs.jpg' WHERE slug = 'free-range-eggs';
UPDATE products SET image_url = '/images/products/French Beans.jpg' WHERE slug = 'french-beans';
UPDATE products SET image_url = '/images/products/Fresh Bananas.jpg' WHERE slug = 'fresh-bananas';
UPDATE products SET image_url = '/images/products/Fresh Orange Juice.jpg' WHERE slug = 'fresh-orange-juice';
UPDATE products SET image_url = '/images/products/Fresh Pineapple.jpg' WHERE slug = 'fresh-pineapple';
UPDATE products SET image_url = '/images/products/Frozen Vegetables.jpg' WHERE slug = 'frozen-vegetables';
UPDATE products SET image_url = '/images/products/Whole Garlic Bulbs.jpg' WHERE slug = 'garlic-bulbs';
UPDATE products SET image_url = '/images/products/Ghee (Cow Milk).jpg' WHERE slug = 'ghee-cow-milk';
UPDATE products SET image_url = '/images/products/Golden Delicious Apples.jpg' WHERE slug = 'golden-delicious-apples';
UPDATE products SET image_url = '/images/products/Grape Fruit.jpg' WHERE slug = 'grape-fruit';
UPDATE products SET image_url = '/images/products/Green Apples.jpg' WHERE slug = 'green-apples';
UPDATE products SET image_url = '/images/products/Green Beans.jpg' WHERE slug = 'green-beans';
UPDATE products SET image_url = '/images/products/Green Capsicum.jpg' WHERE slug = 'green-capsicum';
UPDATE products SET image_url = '/images/products/Groundnut Oil.jpg' WHERE slug = 'groundnut-oil';
UPDATE products SET image_url = '/images/products/Fresh Guava.jpg' WHERE slug = 'guava';
UPDATE products SET image_url = '/images/products/Herbal Green Tea.jpg' WHERE slug = 'herbal-green-tea';
UPDATE products SET image_url = '/images/products/Hibiscus Iced Tea.jpg' WHERE slug = 'hibiscus-iced-tea';
UPDATE products SET image_url = '/images/products/Honey (Raw Wildflower).jpg' WHERE slug = 'honey-raw-wildflower';
UPDATE products SET image_url = '/images/products/Iceberg Lettuce.jpg' WHERE slug = 'iceberg-lettuce';
UPDATE products SET image_url = '/images/products/Iced Coffee.jpg' WHERE slug = 'iced-coffee';
UPDATE products SET image_url = '/images/products/Fresh Jackfruit.jpg' WHERE slug = 'jackfruit';
UPDATE products SET image_url = '/images/products/Jaggery.jpg' WHERE slug = 'jaggery-cane';
UPDATE products SET image_url = '/images/products/Jamun Juice.jpg' WHERE slug = 'jamun-juice';
UPDATE products SET image_url = '/images/products/Jasmine Green Tea.jpg' WHERE slug = 'jasmine-green-tea';
UPDATE products SET image_url = '/images/products/apple.png' WHERE slug = 'java-apple';
UPDATE products SET image_url = '/images/products/Kale Bunch.jpg' WHERE slug = 'kale-bunch';
UPDATE products SET image_url = '/images/products/Kiwi Fruit.jpg' WHERE slug = 'kiwi-fruit';
UPDATE products SET image_url = '/images/products/Kokum Sherbet.jpg' WHERE slug = 'kokum-sherbet';
UPDATE products SET image_url = '/images/products/Langsat.jpg' WHERE slug = 'langsat';
UPDATE products SET image_url = '/images/products/Leek.jpg' WHERE slug = 'leek';
UPDATE products SET image_url = '/images/products/Fresh Lemons.jpg' WHERE slug = 'lemon';
UPDATE products SET image_url = '/images/products/Yardlong Beans.jpg' WHERE slug = 'long-beans';
UPDATE products SET image_url = '/images/products/Longan.jpg' WHERE slug = 'longan';
UPDATE products SET image_url = '/images/products/Lotus Root.jpg' WHERE slug = 'lotus-root';
UPDATE products SET image_url = '/images/products/Fresh Lychee.jpg' WHERE slug = 'lychee';
UPDATE products SET image_url = '/images/products/Malay Gooseberry.jpg' WHERE slug = 'malay-gooseberry';
UPDATE products SET image_url = '/images/products/Mandarin Oranges.jpg' WHERE slug = 'mandarin-oranges';
UPDATE products SET image_url = '/images/products/Mango Lassi.jpg' WHERE slug = 'mango-lassi';
UPDATE products SET image_url = '/images/products/Pomelo.jpg' WHERE slug = 'mangosteen';
UPDATE products SET image_url = '/images/products/Masala Chai.jpg' WHERE slug = 'masala-chai';
UPDATE products SET image_url = '/images/products/Mint Leaves.jpg' WHERE slug = 'mint-leaves';
UPDATE products SET image_url = '/images/products/Moringa Powder.jpg' WHERE slug = 'moringa-powder';
UPDATE products SET image_url = '/images/products/Herbal Moringa Tea.jpg' WHERE slug = 'moringa-tea';
UPDATE products SET image_url = '/images/products/Mung Beans.jpg' WHERE slug = 'mung-beans-green';
UPDATE products SET image_url = '/images/products/Mustard Seeds.jpg' WHERE slug = 'mustard-seeds';
UPDATE products SET image_url = '/images/products/Nannari Sarbath.jpg' WHERE slug = 'nannari-sarbath';
UPDATE products SET image_url = '/images/products/Oats (Rolled).jpg' WHERE slug = 'oats-rolled';
UPDATE products SET image_url = '/images/products/Okra Ladyfinger.jpg' WHERE slug = 'okra-ladyfinger';
UPDATE products SET image_url = '/images/products/Orange Navel.jpg' WHERE slug = 'orange-navel';
UPDATE products SET image_url = '/images/products/Organic Carrots.jpg' WHERE slug = 'organic-carrots';
UPDATE products SET image_url = '/images/products/Pak Choi.jpg' WHERE slug = 'pak-choi';
UPDATE products SET image_url = '/images/products/Paneer Cheese Cubes.jpg' WHERE slug = 'paneer-cheese-cubes';
UPDATE products SET image_url = '/images/products/Fresh Papaya.jpg' WHERE slug = 'papaya';
UPDATE products SET image_url = '/images/products/Passion Fruit.jpg' WHERE slug = 'passion-fruit';
UPDATE products SET image_url = '/images/products/Fresh Peaches.jpg' WHERE slug = 'peaches';
UPDATE products SET image_url = '/images/products/Cold Pressed Peanut Oil.jpg' WHERE slug = 'peanut-oil';
UPDATE products SET image_url = '/images/products/Green Pears.jpg' WHERE slug = 'pear';
UPDATE products SET image_url = '/images/products/Pineapple Vinegar.jpg' WHERE slug = 'pineapple-vinegar';
UPDATE products SET image_url = '/images/products/Fresh Plums.jpg' WHERE slug = 'plums';
UPDATE products SET image_url = '/images/products/Pointed Gourd.jpg' WHERE slug = 'pointed-gourd';
UPDATE products SET image_url = '/images/products/Fresh Pomegranate.jpg' WHERE slug = 'pomegranate';
UPDATE products SET image_url = '/images/products/Pomelo.jpg' WHERE slug = 'pomelo';
UPDATE products SET image_url = '/images/products/Protein shake.jpg' WHERE slug = 'protein-shake';
UPDATE products SET image_url = '/images/products/Pumpkin.jpg' WHERE slug = 'pumpkin';
UPDATE products SET image_url = '/images/products/Pumpkin Seeds.jpg' WHERE slug = 'pumpkin-seeds';
UPDATE products SET image_url = '/images/products/Purple Cabbage.jpg' WHERE slug = 'purple-cabbage';
UPDATE products SET image_url = '/images/products/Organic Quinoa.jpg' WHERE slug = 'quinoa';
UPDATE products SET image_url = '/images/products/Ragi Flour.jpg' WHERE slug = 'ragi-flour-millet';
UPDATE products SET image_url = '/images/products/Rambutan.jpg' WHERE slug = 'rambutan';
UPDATE products SET image_url = '/images/products/Fresh Raspberries.jpg' WHERE slug = 'raspberries';
UPDATE products SET image_url = '/images/products/Raw Peanuts (With Shells).jpg' WHERE slug = 'raw-peanuts';
UPDATE products SET image_url = '/images/products/banana.png' WHERE slug = 'red-banana';
UPDATE products SET image_url = '/images/products/Red Grapes.jpg' WHERE slug = 'red-grapes';
UPDATE products SET image_url = '/images/products/Red Lentils (Masoor).jpg' WHERE slug = 'red-lentils-masoor';
UPDATE products SET image_url = '/images/products/Red Onions.jpg' WHERE slug = 'red-onions';
UPDATE products SET image_url = '/images/products/Ridge Gourd.jpg' WHERE slug = 'ridge-gourd';
UPDATE products SET image_url = '/images/products/Ripe Avocado.jpg' WHERE slug = 'ripe-avocado';
UPDATE products SET image_url = '/images/products/apple.png' WHERE slug = 'rose-apple';
UPDATE products SET image_url = '/images/products/Rose Milk.jpg' WHERE slug = 'rose-milk';
UPDATE products SET image_url = '/images/products/Rose Myrtle.jpg' WHERE slug = 'rose-myrtle';
UPDATE products SET image_url = '/images/products/Salak Snake Fruit.jpg' WHERE slug = 'salak';
UPDATE products SET image_url = '/images/products/Sapodilla.jpg' WHERE slug = 'sapodilla-chiku';
UPDATE products SET image_url = '/images/products/Pressed Sesame Oil.jpg' WHERE slug = 'sesame-oil';
UPDATE products SET image_url = '/images/products/Sesame Seeds.jpg' WHERE slug = 'sesame-seeds-white';
UPDATE products SET image_url = '/images/products/Snake Fruit.jpg' WHERE slug = 'snake-fruit';
UPDATE products SET image_url = '/images/products/Snake Gourd.jpg' WHERE slug = 'snake-gourd';
UPDATE products SET image_url = '/images/products/Soursop.jpg' WHERE slug = 'soursop';
UPDATE products SET image_url = '/images/products/Spring Onions.jpg' WHERE slug = 'spring-onions';
UPDATE products SET image_url = '/images/products/Star Anise.jpg' WHERE slug = 'star-anise';
UPDATE products SET image_url = '/images/products/Star Fruit.jpg' WHERE slug = 'star-fruit';
UPDATE products SET image_url = '/images/products/Fresh Strawberries.jpg' WHERE slug = 'strawberries';
UPDATE products SET image_url = '/images/products/Sugarcane Juice.jpg' WHERE slug = 'sugarcane-juice';
UPDATE products SET image_url = '/images/products/Sunflower Seeds.jpg' WHERE slug = 'sunflower-seeds';
UPDATE products SET image_url = '/images/products/Sweet Corn.jpg' WHERE slug = 'sweet-corn';
UPDATE products SET image_url = '/images/products/Sweet Potato.jpg' WHERE slug = 'sweet-potato';
UPDATE products SET image_url = '/images/products/Fresh Tamarind.jpg' WHERE slug = 'tamarind';
UPDATE products SET image_url = '/images/products/Tamarind Drink.jpg' WHERE slug = 'tamarind-drink';
UPDATE products SET image_url = '/images/products/Tamarind Paste.jpg' WHERE slug = 'tamarind-paste';
UPDATE products SET image_url = '/images/products/Tapioca Flour.jpg' WHERE slug = 'tapioca-flour';
UPDATE products SET image_url = '/images/products/Taro Root.jpg' WHERE slug = 'taro-root';
UPDATE products SET image_url = '/images/products/Tender Coconut Water.jpg' WHERE slug = 'tender-coconut-water';
UPDATE products SET image_url = '/images/products/Turmeric Latte Mix.jpg' WHERE slug = 'turmeric-latte-mix';
UPDATE products SET image_url = '/images/products/Turmeric Powder.jpg' WHERE slug = 'turmeric-powder';
UPDATE products SET image_url = '/images/products/Fresh Turnips.jpg' WHERE slug = 'turnip';
UPDATE products SET image_url = '/images/products/Vetiver Cooler.jpg' WHERE slug = 'vetiver-cooler';
UPDATE products SET image_url = '/images/products/Vine Tomatoes.jpg' WHERE slug = 'vine-tomatoes';
UPDATE products SET image_url = '/images/products/Walnut Kernels.jpg' WHERE slug = 'walnut-kernels';
UPDATE products SET image_url = '/images/products/Watercress.jpg' WHERE slug = 'watercress';
UPDATE products SET image_url = '/images/products/Watermelon.jpg' WHERE slug = 'watermelon';
UPDATE products SET image_url = '/images/products/White Radish.jpg' WHERE slug = 'white-radish';
UPDATE products SET image_url = '/images/products/Whole Black Pepper.jpg' WHERE slug = 'whole-black-pepper';
UPDATE products SET image_url = '/images/products/Yam Purple.jpg' WHERE slug = 'yam-purple';
UPDATE products SET image_url = '/images/products/Yellow Lentils.jpg' WHERE slug = 'yellow-lentils-toor';
UPDATE products SET image_url = '/images/products/Zucchini.jpg' WHERE slug = 'zucchini';
